spring:
  datasource:
    url: jdbc:postgresql://10.3.17.3/test
    username: root
    password: test
    driver-class-name: org.postgresql.Driver
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000

